export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const ALL_CATEGORIES = "ALL_CATEGORIES";
export const GET_PAGINATED_CATEGORIES = "GET_PAGINATED_CATEGORIES";
export const LOAD_START = "LOAD_START";
export const LOAD_END = "LOAD_END";
